use_default_settings: true

server:
  bind_address: "0.0.0.0"
  port: 8080
  secret_key: "change-me-not-used-for-public-access"
  limiter: false
  image_proxy: false

search:
  safe_search: 0
  autocomplete: ""
  formats:
    - html
    - json

ui:
  static_use_hash: true

outgoing:
  request_timeout: 5.0
  max_request_timeout: 10.0
